Squash-revert a bunch of commits
Fixes the build error

Error in ./out/soong/.intermediates/packages/apps/Aperture/app/Aperture/android_common/withres-withoutdex/Aperture.jar:androidx/camera/camera2/internal/Camera2CameraImpl$1.class:
java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
Exception in thread "main" com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ./out/soong/.intermediates/packages/apps/Aperture/app/Aperture/android_common/withres-withoutdex/Aperture.jar:androidx/camera/camera2/internal/Camera2CameraImpl$1.class
	at Version.fakeStackEntry(Version_8.2.2-udc01.java:0)
	at com.android.tools.r8.M.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:5)
	at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:81)
	at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:32)
	at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:31)
	at com.android.tools.r8.R8.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:18)
	at com.android.tools.r8.R8.run(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:3)
	at com.android.tools.r8wrappers.R8Wrapper.main(R8Wrapper.java:99)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
	at com.android.tools.r8.graph.u2.<init>(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:5)
	at com.android.tools.r8.graph.p1.c(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:3)
	at com.android.tools.r8.graph.Q3.b(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:10)
	at com.android.tools.r8.internal.Ga.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:873)
	at com.android.tools.r8.graph.T3.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:44)
	at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:129)
	at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:130)
	at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:128)
	at com.android.tools.r8.graph.T3.b(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:2)
	at com.android.tools.r8.dex.a.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:27)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Suppressed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.android.tools.r8.utils.T0: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
		at com.android.tools.r8.dex.c.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:60)
		at com.android.tools.r8.dex.c.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:9)
		at com.android.tools.r8.dex.c.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:8)
		at com.android.tools.r8.R8.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:44)
		at com.android.tools.r8.R8.b(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:1)
		at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:28)
		at com.android.tools.r8.R8.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:18)
		at com.android.tools.r8.R8.run(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:3)
		at com.android.tools.r8wrappers.R8Wrapper.main(R8Wrapper.java:99)
	Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.utils.T0: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
		at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:605)
		at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981)
		at com.android.tools.r8.utils.d3.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:64)
		at com.android.tools.r8.dex.c.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:41)
		... 8 more
	Caused by: com.android.tools.r8.utils.T0: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null
		at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:149)
		at com.android.tools.r8.utils.R0.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:128)
		at com.android.tools.r8.graph.T3.b(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:2)
		at com.android.tools.r8.dex.a.a(R8_8.2.2-udc01_5e13c494445163188d7e823222320f7b56419224676bc027428d0599d6e06e33:27)
		at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1428)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	Caused by: [CIRCULAR REFERENCE: java.lang.NullPointerException: Cannot invoke "String.length()" because "<parameter1>" is null]